### ISSUE TITLE
Icelandic-to-English and Icelandic-Textual searches stopped working

### ISSUE THREAD

**Issue by bobtodd** [scottsanett/IceDict_QtWidgets#5]
Howdy,

I love IceDict!  Thanks so much for making this great app!

I'm able to use the Old Norse dictionary fine, both forward and in reverse.  But I can't get any results with the modern Icelandic dictionary.  It's not an internet connectivity problem, since I can access the online dictionary via the web browser; but I can't access it through IceDict.

Do you have any suggestions for how I might correct this behavior?

Peace out,
Todd

**Comment by solvar0719** [comment]
Hi Todd,

This issue has been fixed in [v1.9.7](https://github.com/scottsanett/IceDict/releases/tag/1.9.7). Let me know if there is anything else.

Scott

**Comment by bobtodd** [comment]
Awesome.  Seems to be working.  Thanks!

Peace out,
t
